/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrivesRouteImport } from './routes/drives'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesRoute = DrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drives': typeof DrivesRoute
  '/reports': typeof ReportsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drives': typeof DrivesRoute
  '/reports': typeof ReportsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drives': typeof DrivesRoute
  '/reports': typeof ReportsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/drives' | '/reports' | '/companies/$companyId' | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drives' | '/reports' | '/companies/$companyId' | '/companies'
  id:
    | '__root__'
    | '/'
    | '/drives'
    | '/reports'
    | '/companies/$companyId'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrivesRoute: typeof DrivesRoute
  ReportsRoute: typeof ReportsRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives': {
      id: '/drives'
      path: '/drives'
      fullPath: '/drives'
      preLoaderRoute: typeof DrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrivesRoute: DrivesRoute,
  ReportsRoute: ReportsRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
